name: tencent_im_sdk_plugin
description: tencent_im_sdk_plugin由腾讯云即时通信IM标准版Native SDK封装而成，包含了精简版SDK的全部功能。
version: 3.1.7
homepage: https://cloud.tencent.com/product/im

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.0.1
   
dev_dependencies:
  json_serializable: ^4.1.0
flutter:

  plugin:
    platforms:
      android:
        package: com.qq.qcloud.tencent_im_sdk_plugin
        pluginClass: tencent_im_sdk_plugin
      ios:
        pluginClass: TencentImSDKPlugin